name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 18

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Detekt
      run: ./gradlew detektAll

    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.0

    - name: Install dependencies
      run: bundle install

    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: test
    - name: Build and Tests without JUnit Platform
      run: ./gradlew test

    - name: Add useJUnitPlatform setting
      run: |
          sed -i.bak '/tasks.withType(Test) {/a \\
    useJUnitPlatform()' sdk/build.gradle

    - name: Build and Tests with JUnit Platform
      run: ./gradlew test

    - name: Revert build.gradle changes
      run: mv sdk/build.gradle.bak sdk/build.gradle