name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: set up JDK 18
      uses: actions/setup-java@v5
      with:
        java-version: 18
        distribution: temurin

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Detekt
      run: ./gradlew detektAll

    - name: Set up Ruby 3.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install dependencies
      run: bundle install

    - name: Fastlane Action
      uses: maierj/fastlane-action@v3
      with:
        lane: test
    - name: Build and Tests
      run: |
          fastlane test