name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    name: Upload archives
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref:
            main

      - name: Prepare Sonatype Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "${{ secrets.SONATYPE_GPG_FILE }}" > key.gpg.asc
          gpg -d --passphrase "${{ secrets.SONATYPE_GPG_PASSPHRASE }}" --batch "key.gpg.asc" > "$HOME/.gradle/key.gpg"
          echo "signing.keyId=${{ secrets.SONATYPE_GPG_ID }}" >> ~/.gradle/gradle.properties
          echo "signing.password=${{ secrets.SONATYPE_GPG_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=$HOME/.gradle/key.gpg" >> ~/.gradle/gradle.properties
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> ~/.gradle/gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> ~/.gradle/gradle.properties

      - name: Determine module to publish
        id: module
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          if [[ "$TAG_NAME" == sdk_* ]]; then
            echo "Publishing SDK module" >> $GITHUB_OUTPUT
          elif [[ "$TAG_NAME" == nocodes_* ]]; then
            echo "Publishing NoCodes module" >> $GITHUB_OUTPUT
          else
            echo "Unknown tag format: $TAG_NAME"
            exit 1
          fi

      - name: Publish to MavenCentral
        run: |
          if [[ "${{ steps.module.outputs.module }}" == "sdk" ]]; then
            ./gradlew :sdk:publishAndReleaseToMavenCentral
          elif [[ "${{ steps.module.outputs.module }}" == "nocodes" ]]; then
            ./gradlew :nocodes:publishAndReleaseToMavenCentral
          fi
